name: MyWorkflow file
on:
  pull_request:
    branches: [main]

jobs:
  builds:
    # create VM with ubuntu OS
    runs-on: ubuntu-20.04

    steps:
    # first step to say hello
    - name: greeting steps
      run: |
        echo "Hello there"
        
    # This is where i checkout my code
    - name: Checkout my codes
      uses: actions/checkout@v4
    - name: print content of repo
      run: |
        ls

    # this is where i install python
    - name: Installing Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: check version of python
      run: |
        python --version

    # installing dependencies if any
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
        pip install pytest
    # begin test
    - name: Testing with Pytest
      run: |
        pytest

    # this is where we access the hidden repo
    - name: Checkout Hidden Repo
      uses: actions/checkout@v4
      with:
        repository: taufikhazri/UOBHidden
        path: hiddenfolder
        token: ${{secrets.SECRETUOB}}

    - name: discord
      uses: sebastianpopp/discord-action@releases/v2
      with:
        webhook: ${{ secrets.DISCORDSECRET }}
        message: '${{ github.repository }} has been successfully deployed.'


    # this prints out the hidden files
    - name: print out hidden things
      run: |
        ls
        cd hiddenfolder
        ls
