name: MyWorkflow file
on:
  push:
    branches: [main]

jobs:
  bbuilds:
  #create ubuntu vm
    runs-on: ubuntu-latest

    steps:
    #first steps to say hello
      - name: greeting steps
        run:
          echo "Hello there"

      - name: Checkout my codes
        uses: actions/checkout@v4
      - name: print content
        run: |
          ls

      - name: Intsalling Python
        uses: action/setup-python@v5
        with:
          python-version: '3.10'

      - name: check version of python
        run: |
          python --version
